version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - USERNAME=dominik
       - PASSWORD=dom53361.
       - debian:bullseye
       - DEBIAN_FRONTEND=noninteractive
    environment:
      - container docker
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    ports: 
        - 5901:5900
    tty: true
    volumes:
      - ./setup.sh:/root/setup.sh
      - debian_sys:/sys/fs/cgroup:ro
    #restart: unless-stopped

  
volumes:
  debian_sys:

#docker run -it -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/fs/fuse:/sys/fs/fuse  --tmpfs /tmp --tmpfs /run  --tmpfs /run/lock -p 5901:5900 -p 80:80 --cgroupns=host debian-vm
