version: "3"

services:
  debian-vm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - USERNAME=dominik
       - PASSWORD=dom53361.
       - IMAGE=debian:bullseye
       - PHP=true
       - PHP_VERSION=8
       - NODE=true
       - NODE_VERSION=15
       - RUST=true
       - DESKTOP=true
       - DEBIAN_FRONTEND=noninteractive
    environment:
      - container docker
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    ports: 
        - 5901:5900
        - 80:80
    #cgroupns: host
    cgroup_parent: host
    container_name: debian-vm
    tty: true
    #set privilaged to true if you want to use snap or faltpak  
    privileged: false
    volumes:
      - home:/home
      - cgroup:/sys/fs/cgroup
      - fuse:/sys/fs/fuse  
      - opt:/opt
      - sbin:/sbin
      - lib:/lib
      - snap:/snap
      - root:/root
      - usr:/usr
    tmpfs:
      - /tmp
      - /run
      - /run/lock
      - /var/chache
    restart: unless-stopped

  
volumes:
  cgroup:
  home:
  fuse:
  opt:
  sbin:
  lib: 
  snap:
  root:
  usr:
#docker run -it -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/fs/fuse:/sys/fs/fuse  --tmpfs /tmp --tmpfs /run  --tmpfs /run/lock -p 5901:5900 -p 80:80 --cgroupns=host debian-vm
